baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Jericho Cain"
theme = "ananke"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 2

  [[menu.main]]
    identifier = "teaching"
    name = "Teaching"
    url = "/teaching/"
    weight = 3

  [[menu.main]]
    identifier = "astrophotography"
    name = "Astrophotography"
    url = "/astrophotography/"
    weight = 4

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[params]
  custom_css = ["css/custom.css","css/gallery.css"]
